"use client";

import { useCallback, useEffect, useState } from "react";
import Topbar from "@/components/dashboard/Topbar";
import StatCard from "@/components/dashboard/StatCard";

export default function AdminDashboardPage() {
  const [data, setData] = useState(null);

  const load = useCallback(async () => {
    const res = await fetch("/api/admin/dashboard");
    if (res.ok) setData(await res.json());
  }, []);

  useEffect(() => {
    load();
    const interval = setInterval(load, 5000);
    return () => clearInterval(interval);
  }, [load]);

  return (
    <>
      <Topbar title="Admin Dashboard" />
      <div className="space-y-6 p-6">
        {!data ? (
          <div className="animate-pulse text-sm text-ink2">Loading dashboard…</div>
        ) : (
          <>
            {/* TOP ROW: 3 BOXES */}
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
              <div className="rounded-card bg-purple p-6 text-white shadow-lift">
                <p className="text-xs font-semibold uppercase tracking-wider text-purple-tint">All Orders</p>
                <p className="mt-2 font-mono text-3xl font-bold tabular-nums">{data.allOrders}</p>
                <p className="mt-1 text-xs text-white/70">Total orders across all restaurants</p>
              </div>

              <div className="rounded-card bg-white p-6 shadow-soft border border-purple-50">
                <p className="text-xs font-semibold uppercase tracking-wider text-veg">Restaurants Earning</p>
                <p className="mt-2 font-mono text-3xl font-bold tabular-nums text-ink">
                  ₹{data.restaurantsEarning.toFixed(0)}
                </p>
                <p className="mt-1 text-xs text-ink2">Total sales generated by restaurants</p>
              </div>

              <div className="rounded-card bg-white p-6 shadow-soft border border-purple-50">
                <p className="text-xs font-semibold uppercase tracking-wider text-gold">Your Commission</p>
                <p className="mt-2 font-mono text-3xl font-bold tabular-nums text-purple">
                  ₹{data.yourCommission.toFixed(0)}
                </p>
                <p className="mt-1 text-xs text-ink2">Platform earnings from commissions</p>
              </div>
            </div>

            {/* REMAINING 3 BOXES BELOW */}
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
              <StatCard label="No. of Restaurants" value={data.noOfRestaurants} accent="purple" />
              <StatCard label="Active" value={data.active} accent="veg" />
              <StatCard label="Suspended" value={data.suspended} accent="nonveg" />
            </div>

            {/* LIVE RESTAURANT ORDER TABLE BELOW */}
            <div className="rounded-card bg-white shadow-soft p-6">
              <div className="flex items-center justify-between border-b border-purple-50 pb-4">
                <div>
                  <h2 className="font-display text-base font-medium text-ink">Live Restaurant Overview</h2>
                  <p className="text-xs text-ink2">Real-time breakdown of orders, sales, and platform commission.</p>
                </div>
                <span className="font-mono text-xs font-semibold text-purple bg-purple-50 px-3 py-1 rounded-full">
                  ⚡ Auto-refreshing live
                </span>
              </div>

              <div className="mt-4 overflow-x-auto">
                <table className="w-full min-w-[700px] text-left text-sm">
                  <thead>
                    <tr className="border-b border-purple-50 text-xs uppercase tracking-wide text-ink2">
                      <th className="px-4 py-3 font-semibold">Restaurant ID</th>
                      <th className="px-4 py-3 font-semibold">Restaurant Name</th>
                      <th className="px-4 py-3 font-semibold">Orders</th>
                      <th className="px-4 py-3 font-semibold">Earnings</th>
                      <th className="px-4 py-3 font-semibold">Commission</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-purple-50">
                    {data.restaurants.length === 0 ? (
                      <tr>
                        <td colSpan={5} className="px-4 py-8 text-center text-sm text-ink2">
                          No restaurants onboarded yet.
                        </td>
                      </tr>
                    ) : (
                      data.restaurants.map((r) => (
                        <tr key={r.id}>
                          <td className="px-4 py-3.5 font-mono text-xs text-ink2">
                            {r.id.slice(-6).toUpperCase()}
                          </td>
                          <td className="px-4 py-3.5 font-medium text-ink flex items-center gap-2">
                            <span>{r.name}</span>
                            <span
                              className={`rounded-full px-2 py-0.5 text-[10px] font-semibold ${
                                r.status === "ACTIVE" ? "bg-veg-tint text-veg" : "bg-nonveg-tint text-nonveg"
                              }`}
                            >
                              {r.status === "ACTIVE" ? "Active" : "Suspended"}
                            </span>
                          </td>
                          <td className="px-4 py-3.5 font-mono text-xs font-semibold tabular-nums text-ink">
                            {r.orders}
                          </td>
                          <td className="px-4 py-3.5 font-mono text-xs tabular-nums text-ink2">
                            ₹{r.earnings.toFixed(0)}
                          </td>
                          <td className="px-4 py-3.5 font-mono text-xs font-semibold tabular-nums text-purple">
                            ₹{r.commission.toFixed(0)}{" "}
                            <span className="text-[10px] font-normal text-ink2">({r.commissionPercent}%)</span>
                          </td>
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>
              </div>
            </div>
          </>
        )}
      </div>
    </>
  );
}
